version: "2"

services:
  mongo:
    volumes:
      - /data/mongo:/data/db
    image: mongo

  esspunkt:
    build: .
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - /data/upload:/esspunkt60/public/upload
    ports:
      - "5000:5000"
    environment:
      - MONGOADDR=mongo
      - MONGOPORT=27017
      - MONGODB=esspunkt60
      - AUTH=false
    restart: unless-stopped
