version: "2"

services:
  mongo:
    volumes:
      - /data/mongo:/data/db
    image: mongo

  esspunkt:
    image: de1m/esspunkt60
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - /data/upload:/esspunkt60/public/upload
    ports:
      - "5000:5000"
    environment:
      - WEBSOCKETADDR=mongo
      - WEBSOCKETPORT=5000
      - MONGOADDR=mongo
      - MONGOPORT=27017
      - MONGODB=esspunkt60
    restart: unless-stopped
