version: "2"

services:
  mongo:
    volumes:
      - /mongodb:/data/db
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=adminALmfaAf9A
      - MONGODB_APPLICATION_DATABASE=esspunkt60
      - MONGODB_APPLICATION_USER=essen
      - MONGODB_APPLICATION_PASS=essen6003

  esspunkt:
    image: de1m/esspunkt60
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - /app/upload:/esspunkt60/public/upload
    ports:
      - "5000:5000"
    environment:
      - WEBSOCKETADDR=localhost
      - WEBSOCKETPORT=5000
      - MONGOADDR=mongo
      - MONGOPORT=27017
      - MONGODB=esspunkt60
      - MONGOUSER=essen
      - MONGOPASS=essen6003
    restart: unless-stopped
